# Generated by Django 5.2.17 on 2026-10-07 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_admin",
                    models.BooleanField(default=False, verbose_name="申请业务管理员"),
                ),
                (
                    "admin_request_reason",
                    models.TextField(blank=True, verbose_name="申请理由"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "approved_as_admin",
                    models.BooleanField(default=False, verbose_name="批准为业务管理员"),
                ),
                ("review_note", models.TextField(blank=True, verbose_name="审批备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_registration_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_request",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "注册申请",
                "verbose_name_plural": "注册申请",
                "ordering": ["-created_at"],
                "permissions": [
                    ("approve_registration_requests", "可以审批普通成员注册申请")
                ],
            },
        ),
    ]
