# Generated by Django 5.2.17 on 2026-10-06 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("description", models.TextField(verbose_name="需求说明")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("in_progress", "进行中"),
                            ("in_review", "待验收"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "lock_version",
                    models.PositiveIntegerField(default=1, verbose_name="数据版本"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_requirements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责人",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_requirements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提出者",
                    ),
                ),
            ],
            options={
                "verbose_name": "需求",
                "verbose_name_plural": "需求",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AcceptanceCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=500, verbose_name="验收条件")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="demands.requirement",
                        verbose_name="所属需求",
                    ),
                ),
            ],
            options={
                "verbose_name": "验收条件",
                "verbose_name_plural": "验收条件",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("returned", "退回"), ("approved", "通过")],
                        max_length=20,
                        verbose_name="审核结论",
                    ),
                ),
                (
                    "return_reason",
                    models.TextField(blank=True, verbose_name="退回总说明"),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="幂等请求标识",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="审核时间"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requirement_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
            ],
            options={
                "verbose_name": "提交审核",
                "verbose_name_plural": "提交审核",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passed", models.BooleanField(verbose_name="是否通过")),
                ("comment", models.TextField(blank=True, verbose_name="检查说明")),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_results",
                        to="demands.acceptancecriterion",
                        verbose_name="验收条件",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="demands.review",
                        verbose_name="所属审核",
                    ),
                ),
            ],
            options={
                "verbose_name": "逐项验收结果",
                "verbose_name_plural": "逐项验收结果",
                "ordering": ["criterion__sort_order", "criterion_id"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="提交版本")),
                (
                    "result_url",
                    models.URLField(max_length=1000, verbose_name="成果链接"),
                ),
                ("description", models.TextField(verbose_name="完成说明")),
                (
                    "idempotency_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="幂等请求标识",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="demands.requirement",
                        verbose_name="所属需求",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requirement_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交人",
                    ),
                ),
            ],
            options={
                "verbose_name": "成果提交",
                "verbose_name_plural": "成果提交",
                "ordering": ["requirement_id", "version"],
            },
        ),
        migrations.AddField(
            model_name="review",
            name="submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="review",
                to="demands.submission",
                verbose_name="被审核提交",
            ),
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50, verbose_name="操作")),
                (
                    "from_status",
                    models.CharField(blank=True, max_length=20, verbose_name="原状态"),
                ),
                (
                    "to_status",
                    models.CharField(blank=True, max_length=20, verbose_name="新状态"),
                ),
                ("description", models.TextField(blank=True, verbose_name="操作说明")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="附加快照"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requirement_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to="demands.requirement",
                        verbose_name="所属需求",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operation_logs",
                        to="demands.submission",
                        verbose_name="相关提交",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作历史",
                "verbose_name_plural": "操作历史",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="requirement",
            constraint=models.CheckConstraint(
                condition=models.Q(("creator", models.F("assignee")), _negated=True),
                name="requirement_creator_differs_from_assignee",
            ),
        ),
        migrations.AddConstraint(
            model_name="acceptancecriterion",
            constraint=models.UniqueConstraint(
                fields=("requirement", "sort_order"),
                name="unique_criterion_order_per_requirement",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewresult",
            constraint=models.UniqueConstraint(
                fields=("review", "criterion"),
                name="unique_result_per_review_criterion",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                fields=("requirement", "version"),
                name="unique_submission_version_per_requirement",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="submission_version_gte_one",
            ),
        ),
    ]
